name: eksis
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_nav_bar: ^5.0.7
  animated_notch_bottom_bar: ^1.0.3
  flutter_launcher_icons: ^0.13.1 


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/profile_photo.png" 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo/splash.png
    - assets/logo/LOGOMIRING.png
    - assets/logo/images/






